### ISSUE TITLE
DynamoDB Migration

### ISSUE THREAD

**Issue by msluther** [warehouseai/warehouse-models#8]
To support the DynamoDB migration outlined in [this proposal](https://github.com/godaddy/warehouse.ai/blob/master/docs/proposals/moving-to-dynamodb.md):

- `warehouse-models` should be updated to be able to read & write records to DynamoDB
- Uses the `dynamodb` package from npm
- Tests are updated and run against a `localstack` instance of DynamoDB
- Update documentation
- Published as a new major version

**Comment by Swaagie** [comment]
This can be closed right?
